### ISSUE TITLE
Rename -r and -u to -a and -d respectively

### ISSUE THREAD

**Issue by SamTebbs33** [matusf/goto-fish#2]
I think it would be good to rename the "register" and "unregister" actions to "add" and "delete" respectively, as this would more natural and aligned with existing conventions.

**Comment by matusf** [comment]
Hi, thanks for the issue. The reason for using register and unregister is to be compatible with existing [goto](https://github.com/iridakos/goto) project for the bash. So that users switching from bash to fish can move smoothly. Therefore I'd like to keep the existing namings.

**Comment by SamTebbs33** [comment]
Ah that makes a lot of sense
